language: node_js

node_js:
- '6'
- '7'
- '8'

cache:
  yarn: true
  directories:
  - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2
  - export PATH="$HOME/.yarn/bin:$PATH"

script: yarn run test

before_deploy:
- cd packages/ws-intl
- yarn run build

deploy:
  provider: npm
  email: ito@mercateo.com
  api_key:
    secure: uCBvQ606IUAF3qIKVyiKWpthh3JQ7tgcCM1P806hRU269hlrFT+D2E4UKbClZftFqoNASC+/0uThjn077u+AYyi3SqCAhBaQOm9Hj4bIFFZqh9p9IFdPqN6lQ8yOA09flbK0O02ayK0JEHhJBaiGhKqp+OkPEVxs0TR1gT44w28NYpzKWRSAHGwV7AcV7B9uzCbcxsO+/JqCm3MbEvx2GGlfwwtMRddOK+m6kPHGGYj85VpkZ1tl1vw4zEYsS0Es+QE2uqZSbL4y1TX/txkw2cv3NVZTGZ3DYJLm7+vF+lPPodDt948/WMExZUXEP7fqBek3bn/uMxbXJLTVhxFZ1vtqQ8GszIfHWVTczUbNvpX2Zi0Gozr3xU/PFiIBI2Ye88WD22qgCtq7iqWX/ni1g1BWkJOix1wK/Hi8VKzdZNxEL4IJ7CfH680M/P2UrRduJ4dPXzZ2XtdkGO97l4nqCY38d+VKlA/Cvgd3J/MzsnXsyfJOlwXRx+mag5/q30kLfF9GLK2OKJ0Hw++gI54snogmS7ZjKdIOWKelMl1ruSL8txD38KVuUgIXXbTjRhtuFXMnhVUi89Aukcif+ycLb3+gFJ84DrmASKMm+2wFBxZAulNu0xsDMRHnbsZCKXf9OuO/RqpOj2nnHj1d1OEVcDSl5ju1V/4ORok2W1sbD5A=
  on:
    tags: true
    repo: Mercateo/ws-intl
